package org.demo.producer.exception;

public interface ExceptionCode {
    String PROFILE_FIELD_IS_EMPTY = "PROFILE_FIELD_IS_EMPTY";
    String MISSING_FIELDS = "MISSING_FIELDS";
    String LOGIN_IS_ALREADY_USED = "LOGIN_IS_ALREADY_USED";
    String NO_USERS_WITH_LOGIN= "NO_USERS_WITH_LOGIN";
    String INVALID_PASSWORD= "INVALID_PASSWORD";

    String ROLE_IS_ALREADY_EXIST = "ROLE_IS_ALREADY_EXIST";
    String ROLE_IS_NOT_EXIST = "ROLE_NOT_EXIST";
    String PROFILE_IS_ALREADY_EXIST = "PROFILE_IS_ALREADY_EXIST";
    String PROFILE_IS_NOT_EXIST = "PROFILE_IS_NOT_EXIST";
    String PROFILE_ROLE_IS_NOT_EXIST = "ROLE_NOT_EXIST";

    String ITEM_NOT_EXIST = "ITEM_NOT_EXIST";
    String ITEM_ALREADY_EXIST = "ITEM_ALREADY_EXIST";
    String PERMISSION_DENIED = "PERMISSION_DENIED";

    String CUSTOMER_NOT_EXIST = "CUSTOMER_NOT_EXIST";
    String PROVIDER_NOT_EXIST = "PROVIDER_NOT_EXIST";
    String PRODUCT_NOT_EXIST = "PRODUCT_NOT_EXIST";
    String COMMAND_NOT_EXIST = "COMMAND_NOT_EXIST";
    String COMMAND_NOT_PAID = "COMMAND_NOT_PAID";
    String PRICE_INCORRECT = "PRICE_INCORRECT";
}
